# Generated by Django 4.0.2 on 2022-02-05 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_client_alter_article_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_name', models.CharField(max_length=100)),
                ('contact_address', models.CharField(max_length=200)),
                ('contact_mobile', models.CharField(max_length=12)),
                ('contact_email', models.EmailField(max_length=20)),
            ],
        ),
    ]
